apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
    service: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      service: auth
  template:
    metadata:
      labels:
        app: auth
        service: auth
    spec:
      volumes:
      - name: certs-secret
        secret:
          secretName: auth-certs-secret
      containers:
      - name: auth-container
        image: hhana982/auth:dev
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: certs-secret
          mountPath: /etc/secret
        env: 
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-certs-secret
              key: SECRET_KEY
        - name: REFRESH_KEY
          valueFrom:
            secretKeyRef:
              name: auth-certs-secret
              key: REFRESH_KEY
        - name: SECRET_KEYS_PATH
          value: "/etc/secret"