apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    app: auth-db
    service: auth
spec:
  selector:
    app: auth-db
    service: auth
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP